version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: n8n-sso-gateway
    # load your local .env (make sure it defines CASDOOR_* etc.)
    env_file:
      - .env
    # map port 8000 on your host to 8000 in the container
    ports:
      - "8001:8001"
    # for development, mount your code and enable --reload
    volumes:
      - .:/app:cached
    command: >
      uvicorn apps.main:app
      --host 0.0.0.0
      --port 8001
      --reload
    restart: unless-stopped
